### ISSUE TITLE
OCaml module name clash between CoqHammer and Coq master (partac)

### ISSUE THREAD

**Issue by palmskog** [lukaszcz/coqhammer#89]
While compiling the CoqHammer `master` branch with Coq `master` with coq_makefile, I noticed the following warning:
```
CAMLOPT -c -for-pack Hammer_plugin src/plugin/g_hammer.ml
findlib: [WARNING] Interface partac.cmi occurs in several directories: ~/.opam/4.11.1.coqdev/lib/coq/stm, src/plugin
CAMLOPT -pack -o src/plugin/hammer_plugin.cmx
findlib: [WARNING] Interface partac.cmi occurs in several directories: ~/.opam/4.11.1.coqdev/lib/coq/stm, src/plugin
CAMLOPT -a -o src/plugin/hammer_plugin.cmxa
findlib: [WARNING] Interface partac.cmi occurs in several directories: ~/.opam/4.11.1.coqdev/lib/coq/stm, src/plugin
CAMLOPT -shared -o src/plugin/hammer_plugin.cmxs
findlib: [WARNING] Interface partac.cmi occurs in several directories: ~/.opam/4.11.1.coqdev/lib/coq/stm, src/plugin
```
The underlying cause is that Coq's `master` branch introduced a file `stm/partac.ml`, while CoqHammer already has `src/plugin/partac.ml`. The coq_makefile build seems to resolve the conflict properly, but when I tried to build with Dune, I get failures like this:
```
File "./theories/Plugin/Hammer.v", line 2, characters 0-34:
Error:
Dynlink error: The module `Partac' is already loaded (either by the main program or a previously-dynlinked library)
```
So coq_makefile is probably only getting lucky, and there may be more problems due to this clash in the future.

One solution is to rename the CoqHammer `partac.ml` file to something else - maybe `hammer_partac.ml`?

**Comment by SkySkimmer** [comment]
Remove `(wrapped false)` from your dune files to avoid module clashes

**Comment by palmskog** [comment]
I added `(wrapped false)` to make the builds equivalent to the coq_makefile build (which doesn't use wrapping). Here's what I get with `dune build` with `(wrapped false)` removed:
```
File "src/tactics/tactics_main.ml", line 3, characters 5-18:
3 | open Hammer_errors
         ^^^^^^^^^^^^^
Error: Unbound module Hammer_errors
File "src/tactics/sauto.ml", line 55, characters 15-31:
55 |   s_leaf_tac = Utils.ltac_apply "Tactics.leaf_solve" [];
                    ^^^^^^^^^^^^^^^^
Error: The module Utils is an alias for module Hhutils, which is missing
```

**Comment by SkySkimmer** [comment]
Doesn't coq_makefile do something like wrapping when using .mlpack? Try replacing your .mllib by .mlpack

**Comment by lukaszcz** [comment]
It's mllib because the modules are then also used by the hammer plugin
(compiled separately). I remember I couldn't make it work with mlpack

**Comment by palmskog** [comment]
By changing to `.mlpack` and inserting some `open Hammer_lib` and `open Hammer_tactics` in the right places I made it compile both with coq_makefile and Dune. 

@lukaszcz should I modify PR #90 to include this change? This means there is no need to change `partac.ml` to `hammer_partac.ml`, so this would be rolled back.

**Comment by lukaszcz** [comment]
Are you sure it works if you first compile the tactics (make tactics),
install them (make install-tactics) and then compile the plugin only (make
plugin)? Are you sure plugin compilation doesn't use older versions of
tactics which you had installed and forgot to remove?

**Comment by palmskog** [comment]
@lukaszcz the following sequence works fine for me locally with `.mlpack` in a dedicated opam switch:
```shell
make tactics
make install-tactics
make plugin
```
Also, the CI essentially does the same thing and [passed](https://travis-ci.org/github/lukaszcz/coqhammer/builds/734753832).

**Comment by lukaszcz** [comment]
Ok, then we can change it to mlpack. Somehow this didn't work for me
sometime ago, but I don't remember the details now

**Comment by lukaszcz** [comment]
I understand this is solved now.
